#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.1 on Tue Dec 26 22:55:18 2017
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
import gettext
from LoginDialog import LoginDialog

class LoginApp(wx.App):
				def OnInit(self):
								Login = LoginDialog(None, wx.ID_ANY, "")
								self.SetTopWindow(Login)
								Login.Show()
								return True

# end of class LoginApp

if __name__ == "__main__":
				gettext.install("login") # replace with the appropriate catalog name

				login = LoginApp(0)
				login.MainLoop()