# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.1 on Tue Dec 26 22:55:18 2017
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class LoginDialog(wx.Dialog):
				def __init__(self, *args, **kwds):
								# begin wxGlade: LoginDialog.__init__
								kwds["style"] = wx.STAY_ON_TOP
								wx.Dialog.__init__(self, *args, **kwds)
								self.loginHeaderText = wxLoginHeaderText(self, wx.ID_ANY, _("Please Login"), style=wx.ALIGN_CENTER_HORIZONTAL)
								self.loginName = wxLoginNameText(self, wx.ID_ANY, _("Name"), style=wx.ALIGN_CENTER_HORIZONTAL)
								self.loginEntry = wxLoginEntryCtrl(self, wx.ID_USERNAME, "", style=wx.TE_PROCESS_TAB)
								self.loginPassword = wxLoginPassText(self, wx.ID_ANY, _("Password"), style=wx.ALIGN_CENTER_HORIZONTAL)
								self.loginPassEntry = wxLoginPassCtrl(self, wx.ID_PASSWORD, "", style=wx.TE_NO_VSCROLL | wx.TE_PASSWORD | wx.TE_PROCESS_ENTER | wx.TE_PROCESS_TAB)
								self.loginButton = wxLoginOKButton(self, wx.ID_OK, "")
								self.cancelutton = wx.Button(self, wx.ID_CANCEL, "")

								self.__set_properties()
								self.__do_layout()
								# end wxGlade

				def __set_properties(self):
								# begin wxGlade: LoginDialog.__set_properties
								self.SetTitle(_("dialog_1"))
								self.SetBackgroundColour(wx.Colour(192, 192, 192))
								self.SetForegroundColour(wx.Colour(33, 33, 33))
								self.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
								self.SetToolTip(wx.ToolTip(_("Please Login")))
								self.SetFocus()
								self.loginHeaderText.SetFont(wx.Font(18, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Noto Sans"))
								self.loginHeaderText.SetToolTip(wx.ToolTip(_("Login")))
								self.loginName.SetToolTip(wx.ToolTip(_("Name")))
								self.loginEntry.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Noto Sans"))
								self.loginEntry.SetToolTip(wx.ToolTip(_("Name")))
								self.loginEntry.SetFocus()
								self.loginPassword.SetToolTip(wx.ToolTip(_("Password")))
								self.loginPassEntry.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Noto Sans"))
								self.loginPassEntry.SetToolTip(wx.ToolTip(_("Password")))
								self.loginButton.SetDefault()
								# end wxGlade

				def __do_layout(self):
								# begin wxGlade: LoginDialog.__do_layout
								loginSizer = wx.BoxSizer(wx.VERTICAL)
								loginFooter = wx.BoxSizer(wx.HORIZONTAL)
								loginFooterGrid = wx.GridSizer(1, 4, 0, 0)
								loginBody = wx.BoxSizer(wx.HORIZONTAL)
								loginBodyGrid = wx.GridSizer(3, 2, 5, 5)
								loginHeader = wx.BoxSizer(wx.HORIZONTAL)
								loginHeadGrid = wx.GridSizer(1, 3, 0, 40)
								loginHeader.Add((50, 50), 0, wx.ALIGN_CENTER | wx.SHAPED, 0)
								loginHeadGrid.Add(self.loginHeaderText, 0, wx.ALIGN_CENTER | wx.SHAPED, 0)
								loginHeader.Add(loginHeadGrid, 1, 0, 0)
								loginHeader.Add((50, 50), 0, wx.ALIGN_CENTER | wx.SHAPED, 0)
								loginSizer.Add(loginHeader, 1, wx.ALIGN_CENTER | wx.SHAPED, 0)
								loginBody.Add((50, 50), 0, wx.ALIGN_CENTER | wx.SHAPED, 0)
								loginBodyGrid.Add(self.loginName, 0, wx.ALIGN_RIGHT | wx.SHAPED, 0)
								loginBodyGrid.Add(self.loginEntry, 0, wx.EXPAND, 0)
								loginBodyGrid.Add(self.loginPassword, 0, wx.ALIGN_RIGHT | wx.SHAPED, 0)
								loginBodyGrid.Add(self.loginPassEntry, 0, wx.EXPAND, 0)
								loginBodyGrid.Add(self.loginButton, 0, wx.ALL | wx.EXPAND, 5)
								loginBodyGrid.Add(self.cancelutton, 0, wx.ALL | wx.EXPAND, 5)
								loginBody.Add(loginBodyGrid, 1, wx.ALIGN_CENTER | wx.EXPAND | wx.SHAPED, 0)
								loginBody.Add((50, 50), 0, wx.ALIGN_CENTER | wx.SHAPED, 0)
								loginSizer.Add(loginBody, 1, wx.ALIGN_CENTER | wx.SHAPED, 0)
								loginFooter.Add((50, 50), 0, wx.ALIGN_CENTER | wx.SHAPED, 0)
								loginFooter.Add(loginFooterGrid, 1, wx.ALIGN_CENTER | wx.SHAPED, 0)
								loginFooter.Add((50, 50), 0, wx.ALIGN_CENTER | wx.SHAPED, 0)
								loginSizer.Add(loginFooter, 1, wx.ALIGN_CENTER | wx.SHAPED, 1)
								self.SetSizer(loginSizer)
								loginSizer.Fit(self)
								self.Layout()
								# end wxGlade

# end of class LoginDialog
