version: "3.9"
services:
  api:
    build:  ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
    environment:
      FLASK_ENV: development
  web:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - api